INSERT INTO "analytics" VALUES (1, 'How To Read', 'views/DASHBOARDFORTELKOMSEL/HowToRead', 1, '0', NULL, NULL, NULL);
INSERT INTO "analytics" VALUES (2, 'General Over', 'views/DASHBOARDFORTELKOMSEL/01_GENERAL_OVERVIEW_1', 1, '0', NULL, NULL, NULL);
